### ISSUE TITLE
Libraries included with Arduino not working

### ISSUE THREAD

**Issue by tyilo** [geetarista/ST2-Arduino#1]
This doesn't support including libraries coming with the Arduino application.

For example, this will not compile:

```
#include <LiquidCrystal.h>

LiquidCrystal lcd(10, 11, 12, 13, 14, 15, 16);

void setup()
{
    lcd.begin(16, 2);
    lcd.print("hello world");
}

void loop()
{
    // do nothing
}
```

It gives this error:

```
applet/test.cpp:2:27: error: LiquidCrystal.h: No such file or directory
applet/test.cpp:4: error: 'LiquidCrystal' does not name a type
applet/test.cpp: In function 'void setup()':
applet/test.cpp:8: error: 'lcd' was not declared in this scope
make: *** [applet/test.o] Error 1
[Finished in 0.5s with exit code 2]
```

I am using Mac OS X 10.8 with the 1.0.1 version of the Arduino application.

**Comment by tyilo** [comment]
The directories where the libraries reside are `/Applications/Arduino.app/Contents/Resources/Java/libraries` for libraries included with Arduino and `~/Documents/Arduino/libraries` for user installed libraries.

**Comment by b3by** [comment]
It worked for me changing in:

```
#include "LiquidCrystal.h"
```
