### ISSUE TITLE
Undefined reference to `main`

### ISSUE THREAD

**Issue by tyilo** [geetarista/ST2-Arduino#10]
When building any `.ino` file that works fine with `ino build`, I get following error:

```
Linking firmware.elf
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/lib/avr5/crtm328p.o:(.init9+0x0): undefined reference to `main'
make: *** [.build/uno/firmware.elf] Error 1
Make failed with code 2
[Finished in 0.6s with exit code 1]
```

Example `ino`-file:

```
void setup() 
{ 
    // Nothing
}

void loop()
{
    // Nothing
}
```

**Comment by geetarista** [comment]
What version of Sublime Text and Arduino.app do you have?

**Comment by geetarista** [comment]
Also, how exactly are you installing this plugin? You mentioned using Package Control, but I just tried it and I don't see the Arduino menu anywhere...

**Comment by tyilo** [comment]
Sublime Text 2.0.1, build 2217
Arduino 1.0.2

I installed it by doing:
- cmd shift p, "Package Control: Add Repository"
- "https://github.com/geetarista/ST2-Arduino/"
- cmd shift p, "Package Control: Install Package"
- "ST2-Arduino"

**Comment by geetarista** [comment]
OK, I'm going to have to wait until I get home when I can test with my Arduino. Hopefully I can have a solution for you soon.

**Comment by tyilo** [comment]
I didn't have the correct directory structure for `ino` (`foo/src/foo.ino`).
Making the `src` directory it now works perfect.

**Comment by geetarista** [comment]
Awesome! I'll probably need to add more documentation to the README about `ino` since most people aren't going to read their entire docs.

Thanks for helping to make the plugin better. :smiley:

**Comment by tyilo** [comment]
Also look out for this feature request, which may allow what I want to do: https://github.com/amperka/ino/issues/65
:smile:
