### ISSUE TITLE
Keyboard shortcut for compile command

### ISSUE THREAD

**Issue by ghost** [geetarista/ST2-Arduino#4]
No matter what I do I can't seem to create a keyboard shortcut for the "compile" command. "upload" works without issue. I've tried multiple values for the specific key used by the compile command.

```
[
    { "keys": ["super+ctrl+shift+c"], "command": "complie" },
    { "keys": ["super+ctrl+shift+u"], "command": "upload"}
]
```

Also, is it possible to create a combo command: compile the sketch and if the compile is successful then execute the upload command? I'd then like to create a shortcut key for that.

Thanks!
Reed

**Comment by tyilo** [comment]
Maybe you should make the value of the command `compile` and not `complie` ;)
