### ISSUE TITLE
Errno 2 - no such file or directory

### ISSUE THREAD

**Issue by jhembach** [geetarista/ST2-Arduino#5]
On trying to compile or upload, I get this:

[Errno 2] No such file or directory
[cmd:  [u'make', u'-e', u'-f', u'/Users/jhembach/Library/Application Support/Sublime Text 2/Packages/ST2-Arduino/Support/Makefile']]
[dir:  /Users/jhembach/Documents/Arduino/hmxClock_v8]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

The folder and file definitely do exist though. I get this whether the package was installed manually or through package manager.

Also, Tools -> Arduino -> Monito USB port is greyed out in the menu. What am I missing / doing wrong here? Thanks.

**Comment by ghost** [comment]
Hey,

I too am having trouble compiling/uploading my **own** sketches. If I open one of the Arduino example sketches (like Blink) it compiles and uploads fine. I have no idea why this is occurring.

And iirc the Monitor USB port menu item has always been grayed out for me.

**Comment by peterrus** [comment]
Having the same problem, OS = Windows 7

**Comment by andrewmovic** [comment]
Hi,
I am facing same problem in mac os x ml

Errno 2] No such file or directory
[cmd:  [u'make', u'-e', u'-f', u'/Users/andrew/Library/Application Support/Sublime Text 2/Packages/ST2-Arduino/Support/Makefile']]
[dir:  /Applications/Arduino.app/Contents/Resources/Java/examples/01.Basics/Blink]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]

I have already checked the directory under arduino IDE, nothing missing..
any idea?

**Comment by exchgr** [comment]
Open Sublime Text 2 from the command line and this problem goes away. Sublime Text 2 will only inherit your $PATH if there's a $PATH to begin with, and there's no $PATH unless you're in the terminal.

**Comment by geetarista** [comment]
Can you all try a newer build of the plugin? I'm trying to use a different tool called ino that should make it easier to handle building cross platform instead of making the plugin do it.

**Comment by tyilo** [comment]
I still get this error with the newest build.

**Comment by geetarista** [comment]
@Tyilo What is the stacktrace you get with the newest build? It should be very different now that it uses ino. Also, please let me know if you installed ino as directed in the README or some other method.

**Comment by tyilo** [comment]
```
[Errno 2] No such file or directory
[cmd:  [u'ino', u'build']]
[dir:  /Users/Tyilo/Documents/Arduino]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

I followed the README, except I used Package Control for installing and `pip` for installing `ino`, as the github version failed to work.

`ino` is located in `/usr/local/bin`

**Comment by geetarista** [comment]
Is `/usr/local/bin` in your $PATH? The reason I don't qualify the path for `ino` is that I will never know exactly where a user will have it installed. I'll probably have to add a note in the README if that's the case.

**Comment by tyilo** [comment]
How can I add something to my Sublime Text 2 PATH?
This doesn't seem to work:

```
"env": {
        "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    }
```

**Comment by geetarista** [comment]
This should come from the global variable from your shell. I don't know if you can do something like this in Sublime Text. In your case, you would add the following after this line https://github.com/Tyilo/dotfiles/blob/master/.zshrc#L58:

``` bash
export PATH=$PATH:/usr/local/bin
```

**Comment by tyilo** [comment]
It is already there ;), look at line 52...

**Comment by geetarista** [comment]
Ah, I missed that. Then somehow Sublime Text isn't picking up the right $PATH when running the command. And to be sure, when you're in your terminal `echo $PATH` looks correct?

I'm going to have to look into how Sublime Text handles environment variables. In my case, I have `ino` in `/usr/local/bin` as well, but it works for me.

Also, which platform are you on?

**Comment by tyilo** [comment]
I'm on OS X, it works fine if I launch sublime from terminal (`open -a "Sublime Text 2"`), however when opening sublime normally from the Dock or in Finder, it doesn't pick up the PATH.

**Comment by geetarista** [comment]
Ah, that may be it. I always use the `subl` command to open a project from the terminal. What I'll do is add a ridiculous `path` setting to the build command and that way it should pick it up as long as someone isn't doing anything too crazy.

Give me a few minutes and I'll push up a commit.

**Comment by tyilo** [comment]
Cool, thanks.

**Comment by geetarista** [comment]
OK, just pushed. Try that out and let me know if it helps.

**Comment by tyilo** [comment]
Now this works, however I still can't build anything because of #10.

**Comment by geetarista** [comment]
Awesome. That should at least fix this issue for everyone else now as well.
