### ISSUE TITLE
Change path to ino

### ISSUE THREAD

**Issue by danylevskyi** [geetarista/ST2-Arduino#9]
Thank you very much for this beautiful plugin! It works like a charm on Linux.
I would like to ask if there is an opportunity to change a path to 'ino'?

{
  "cmd": ["/usr/local/share/python/ino", "build"],
  "selector": "source.c++.arduino",
  "working_dir": "$file_path/.."
}

How to override path?

**Comment by danylevskyi** [comment]
Fixed with 59e20fafd67c046033057d4dbddc5fdabb7b9eb2

**Comment by geetarista** [comment]
Hey, sorry Danny, I accidentally referenced the wrong issue in my commit, so it didn't send you a notification before. :/
